//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowroom.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.ImageCar = new HashSet<ImageCar>();
            this.OrderCar = new HashSet<OrderCar>();
        }
    
        public int id { get; set; }
        public Nullable<int> IdModelСar { get; set; }
        public Nullable<int> IdBody { get; set; }
        public Nullable<int> idTransmission { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<int> idEngine { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> idDiler { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual BodyCar BodyCar { get; set; }
        public virtual Diler Diler { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual ModelCar ModelCar { get; set; }
        public virtual Transmission Transmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageCar> ImageCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCar { get; set; }
    }
}
