//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowroom.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTransaction
    {
        public int id { get; set; }
        public Nullable<int> idOrderCar { get; set; }
        public Nullable<System.DateTime> DataBuy { get; set; }
    
        public virtual OrderCar OrderCar { get; set; }
    }
}
