//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowroom.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarShowroomEntities : DbContext
    {
        public CarShowroomEntities()
            : base("name=CarShowroomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyCar> BodyCar { get; set; }
        public virtual DbSet<BrandCar> BrandCar { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Diler> Diler { get; set; }
        public virtual DbSet<Engine> Engine { get; set; }
        public virtual DbSet<HistoryTransaction> HistoryTransaction { get; set; }
        public virtual DbSet<ImageCar> ImageCar { get; set; }
        public virtual DbSet<ModelCar> ModelCar { get; set; }
        public virtual DbSet<OrderCar> OrderCar { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transmission> Transmission { get; set; }
    }
}
